sudo: required
language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get -qq update
 - sudo apt-get -y install python-fuse python-xattr python-rarfile
   # - pip install fusepy xattr
 - pip install rarfile
 - python setup.py build
script: cd t; ./test-read.py
